resources:
- name: console-src
  image: dnab/git
  options:
    repository: ${env.CONSOLE_SRC_GIT_URI}
    private_key: ${secrets.CONSOLE_SRC_PRIVATE_KEY}

- name: console-s3
  image: dnab/s3
  options:
    username: ${secrets.S3_USERNAME}
    password: ${secrets.S3_PASSWORD}
    bucket: ${secrets.S3_BUCKET}

- name: slack-notification
  image: dnab/slack-alert
  options:
    webhook: ${secrets.SLACK_ALERT_WEBHOOK}

jobs:
- name: test-console
  description: |
    Run automated tests against the console codebase to ensure things are working as intended still
    after some changes have been made.
  tasks:
  - pull: console-src
    trigger: true
  - exec: test
    file: console-src/ci/tasks/test.yml
    input_mapping: { console: console-src }
  - push: console-s3
    params: { input: [ console-src ] }
    when:
    - ${resources.console-src.branch} == 'master'
  defer:
  - put: slack-notification
    params: { status: "${job.status}" }
    when:
    - ${resources.console-src.branch} in ['master', 'feature/*']
